# Generated by Django 5.2.12 on 2026-03-16 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_user_api_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_plan_name',
            field=models.CharField(blank=True, default='Free', max_length=64),
        ),
    ]
