# Generated by Django 5.2.12 on 2026-03-16 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_user_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_ai_model_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_ai_provider',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
