# Generated by Django 5.2.11 on 2026-04-21 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_crypto_billing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='plan_expires_at',
        ),
    ]
