# Generated by Django 5.2.12 on 2026-03-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_add_message_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageattachment',
            name='file_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='file',
            field=models.FileField(blank=True, max_length=500, upload_to='attachments/%Y/%m/%d/'),
        ),
    ]
